"""add attributes to model

Revision ID: 54c3fc1a526d
Revises: d7a17a416dab
Create Date: 2023-11-15 15:26:42.103524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c3fc1a526d'
down_revision = 'd7a17a416dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('body')
        batch_op.drop_column('created_at')
        batch_op.drop_column('username')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('body', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
